import type {
  AppSettings,
  ApiProxyStatus,
  CloudflaredStatus,
} from "../../src/types/app";

export const DEFAULT_SETTINGS: AppSettings = {
  launchAtStartup: false,
  trayUsageDisplayMode: "oneWeekRemaining",
  trayUsageTitleShowWindowLabels: false,
  macosTrayProxyPool: false,
  macosTrayTextIconStyle: "codexTools",
  windowsTrayIconStyle: "gradientNumberPlate",
  trayQuotaIconVisible: true,
  macosTrayLogoRingShowPercentage: true,
  windowsTaskbarWidgetPlacement: "left",
  windowsQuotaOnboardingCompleted: true,
  macosQuotaOnboardingCompleted: true,
  launchCodexAfterSwitch: true,
  smartSwitchIncludeApi: false,
  launchCodexAsAdmin: false,
  codexLaunchPath: null,
  syncOpencodeOpenaiAuth: false,
  restartOpencodeDesktopOnSwitch: false,
  restartEditorsOnSwitch: false,
  restartEditorTargets: [],
  autoStartApiProxy: false,
  apiProxyPort: 8787,
  apiProxyLoadBalanceMode: "average",
  accountOrder: [],
  apiProxySequentialFiveHourLimitPercent: 80,
  apiProxyDisabledModels: [],
  autoAccountWarmupEnabled: false,
  autoAccountWarmupScheduleEnabled: false,
  autoAccountWarmupStartMinute: 360,
  autoAccountWarmupEndMinute: 1320,
  autoAccountWarmupAccountIds: [],
  codexAnalyticsWeeklyBudgetUsd: null,
  remoteServers: [],
  locale: "zh-CN",
  skippedUpdateVersion: null,
};
export const DEFAULT_API_PROXY_STATUS: ApiProxyStatus = {
  running: false,
  port: null,
  apiKey: null,
  baseUrl: null,
  lanBaseUrl: null,
  codexProxyBound: false,
  codexProxyRestoreAvailable: false,
  codexProxyBaseUrl: null,
  codexProxyConfigPath: null,
  activeAccountKey: null,
  activeAccountId: null,
  activeAccountLabel: null,
  lastError: null,
};
export const DEFAULT_CLOUDFLARED_STATUS: CloudflaredStatus = {
  installed: false,
  binaryPath: null,
  running: false,
  tunnelMode: null,
  publicUrl: null,
  customHostname: null,
  useHttp2: false,
  lastError: null,
};
