import type { ApiProxyPanelProps } from "../../src/components/proxy/types";
import {
  DEFAULT_API_PROXY_STATUS,
  DEFAULT_CLOUDFLARED_STATUS,
} from "./defaults";

const noop = () => {};
export function proxyProps(
  overrides: Partial<ApiProxyPanelProps> = {},
): ApiProxyPanelProps {
  return {
    status: DEFAULT_API_PROXY_STATUS,
    cloudflaredStatus: DEFAULT_CLOUDFLARED_STATUS,
    apiProxyKeys: [],
    apiProxyKeyLogs: [],
    apiProxyKeysLoading: false,
    apiProxyUsageStats: null,
    apiProxyUsageRange: "24h",
    apiProxyUsageMetric: "calls",
    apiProxyUsageLoading: false,
    apiProxyUsageClearing: false,
    apiProxyUsageExporting: false,
    accountCount: 0,
    autoStartEnabled: false,
    savedPort: 8787,
    loadBalanceMode: "average",
    sequentialFiveHourLimitPercent: 80,
    apiProxySupportedModels: ["gpt-5.4", "gpt-5.4-mini"],
    apiProxyDisabledModels: [],
    remoteServers: [],
    remoteStatuses: {},
    remoteLogs: {},
    savingSettings: false,
    starting: false,
    stopping: false,
    refreshingApiKey: false,
    bindingCodexProxy: false,
    restoringCodexProxy: false,
    savingApiProxyKey: false,
    refreshingRemoteId: null,
    deployingRemoteId: null,
    startingRemoteId: null,
    stoppingRemoteId: null,
    readingRemoteLogsId: null,
    installingDependencyName: null,
    installingDependencyTargetId: null,
    installingCloudflared: false,
    startingCloudflared: false,
    stoppingCloudflared: false,
    onStart: noop,
    onStop: noop,
    onCreateApiProxyKey: noop,
    onUpdateApiProxyKey: noop,
    onDeleteApiProxyKey: noop,
    onRegenerateApiProxyKey: noop,
    onSelectApiProxyUsageRange: noop,
    onSelectApiProxyUsageMetric: noop,
    onExportApiProxyUsage: noop,
    onClearApiProxyUsageStats: noop,
    onRefreshApiKey: noop,
    onBindCodexProxy: noop,
    onRestoreCodexProxy: noop,
    onRefresh: noop,
    onToggleAutoStart: noop,
    onPersistPort: noop,
    onUpdateLoadBalanceMode: noop,
    onUpdateSequentialFiveHourLimitPercent: noop,
    onUpdateApiProxyDisabledModels: noop,
    onUpdateRemoteServers: noop,
    onRefreshRemoteStatus: noop,
    onDeployRemote: noop,
    onStartRemote: noop,
    onStopRemote: noop,
    onReadRemoteLogs: noop,
    onPickLocalIdentityFile: async () => null,
    onRefreshCloudflared: noop,
    onInstallCloudflared: noop,
    onStartCloudflared: noop,
    onStopCloudflared: noop,
    ...overrides,
  };
}
